# === Stuck review =============================================================
# From the research branch of https://github.com/YashveerR/arc-agi-3-solution
# (research/stuck_review/). When one level has used REVIEW_TOKENS generated
# tokens without being completed, the model is asked to review the ideas it
# rejected on that level and re-test any that were ruled out by an unfair test.
# Nothing is removed from its context; review n on a level fires at n x REVIEW_TOKENS.
#
# Paste as a NEW cell directly AFTER section "1. Environment and submission mode"
# (the cell that applies Franzen's harness patch) and BEFORE "2. Precaching".
# Delete the old fresh-start cell first, if it is still there.
#
# AB_TEST = True is for local measurement runs (bm.n_passes = 2): every game gets
# reviews on one pass and not on the other, and both are logged. Set it to False
# before submitting, so that every game gets reviews.
REVIEW_TOKENS = 40000   # generated tokens on one level per review; 0 switches it off
REVIEW_MAX = 2          # reviews allowed per level
AB_TEST = True

import base64, hashlib, os, subprocess
from pathlib import Path

_PATCH_SHA256 = "ef767605ceefaf9a4431dd484d092976d9e63938a3c4fe2f81951478ff10b743"
_PATCH_B64 = (
    "ZGlmZiAtLWdpdCBhL0FSQzMtSW5mZXJlbmNlL2luZmVyZW5jZS9hZ2VudC90b29sX2FnZW50LnB5"
    "IGIvQVJDMy1JbmZlcmVuY2UvaW5mZXJlbmNlL2FnZW50L3Rvb2xfYWdlbnQucHkKaW5kZXggODRh"
    "OWNkZC4uOTIxOGVkNSAxMDA2NDQKLS0tIGEvQVJDMy1JbmZlcmVuY2UvaW5mZXJlbmNlL2FnZW50"
    "L3Rvb2xfYWdlbnQucHkKKysrIGIvQVJDMy1JbmZlcmVuY2UvaW5mZXJlbmNlL2FnZW50L3Rvb2xf"
    "YWdlbnQucHkKQEAgLTEyMiw2ICsxMjIsNTcgQEAgZGVmIF9sZXZlbF90cmFuc2Zlcl9ndWlkYW5j"
    "ZV9lbmFibGVkKCkgLT4gYm9vbDoKICAgICByZXR1cm4gX2dldF9lbnZfYm9vbCgiQVJDM19MRVZF"
    "TF9UUkFOU0ZFUl9HVUlEQU5DRSIsIEZhbHNlKQogCiAKK2RlZiBfc3R1Y2tfcmV2aWV3X3Rva2Vu"
    "cygpIC0+IGludDoKKyAgICAiIiJHZW5lcmF0ZWQgdG9rZW5zIG9uZSBsZXZlbCBtYXkgdXNlLCB3"
    "aXRob3V0IGJlaW5nIGNvbXBsZXRlZCwgYmVmb3JlIHRoZQorICAgIG1vZGVsIGlzIGFza2VkIHRv"
    "IHJldmlldyB0aGUgaWRlYXMgaXQgaGFzIHJlamVjdGVkIChBUkMzX1NUVUNLX1JFVklFV19UT0tF"
    "TlMpLgorCisgICAgUmV2aWV3IG4gb24gYSBsZXZlbCBmaXJlcyBhdCBuIHRpbWVzIHRoaXMgbWFu"
    "eSB0b2tlbnMuIDAsIHRoZSBkZWZhdWx0LAorICAgIGRpc2FibGVzIHJldmlld3MsIHNvIHRoZSBo"
    "YXJuZXNzIGJlaGF2ZXMgZXhhY3RseSBhcyBiZWZvcmUgdW5sZXNzIHRoaXMgaXMgc2V0LgorICAg"
    "ICIiIgorICAgIHJldHVybiBtYXgoMCwgX2dldF9lbnZfaW50KCJBUkMzX1NUVUNLX1JFVklFV19U"
    "T0tFTlMiLCAwKSkKKworCitkZWYgX3N0dWNrX3Jldmlld19tYXhfcGVyX2xldmVsKCkgLT4gaW50"
    "OgorICAgICIiIkhvdyBtYW55IHJldmlld3Mgb25lIGxldmVsIG1heSBnZXQgKEFSQzNfU1RVQ0tf"
    "UkVWSUVXX01BWCwgZGVmYXVsdCAyKS4iIiIKKyAgICByZXR1cm4gbWF4KDAsIF9nZXRfZW52X2lu"
    "dCgiQVJDM19TVFVDS19SRVZJRVdfTUFYIiwgMikpCisKKworZGVmIF9zdHVja19yZXZpZXdfYWIo"
    "KSAtPiBib29sOgorICAgICIiIkFSQzNfU1RVQ0tfUkVWSUVXX0FCLCBmb3IgbWVhc3VyZW1lbnQg"
    "cnVucyBvbmx5OiBlYWNoIGdhbWUgZ2V0cyByZXZpZXdzIG9uCisgICAgb25lIHBhc3MgYW5kIG5v"
    "dCBvbiB0aGUgb3RoZXIgKHNlZSBfc3R1Y2tfcmV2aWV3X2FybV9vbikuIFRoZSBwYXNzIHdpdGhv"
    "dXQKKyAgICB0aGVtIHJlY29yZHMgd2hlcmUgYSByZXZpZXcgd291bGQgaGF2ZSBmaXJlZCwgc28g"
    "Ym90aCBoYWx2ZXMgb2Ygb25lIHJ1biBjYW4KKyAgICBiZSBjb21wYXJlZCBhdCB0aGUgc2FtZSB0"
    "cmlnZ2VyIHBvaW50LiIiIgorICAgIHJldHVybiBfZ2V0X2Vudl9ib29sKCJBUkMzX1NUVUNLX1JF"
    "VklFV19BQiIsIEZhbHNlKQorCisKK2RlZiBfc3R1Y2tfcmV2aWV3X2FybV9vbihnYW1lX2lkOiBz"
    "dHIsIHBhc3NfaW5kZXg6IGludCkgLT4gYm9vbDoKKyAgICAiIiJEZXRlcm1pbmlzdGljIEEvQiBh"
    "c3NpZ25tZW50OiBhbHRlcm5hdGVzIGJldHdlZW4gcGFzc2VzIG9mIGEgZ2FtZSwgYW5kCisgICAg"
    "c3RhcnRzIG9uIGEgZGlmZmVyZW50IHBhc3MgZm9yIGRpZmZlcmVudCBnYW1lcyBzbyBuZWl0aGVy"
    "IGFybSBpcyBhbHdheXMKKyAgICBwYXNzIDAgKHdoaWNoIHRoZSBzY2hlZHVsZXIgb3JkZXJzIGZp"
    "cnN0KS4iIiIKKyAgICByZXR1cm4gKHN1bShzdHIoZ2FtZV9pZCkuZW5jb2RlKCkpICsgaW50KHBh"
    "c3NfaW5kZXgpKSAlIDIgPT0gMQorCisKK19TVFVDS19SRVZJRVdfTk9URSA9ICgKKyAgICAiUkVW"
    "SUVXIENIRUNLUE9JTlQgT04gTEVWRUwge2xldmVsfS4gWW91IGhhdmUgdXNlZCBhYm91dCB7dG9r"
    "ZW5zX2t9ayBnZW5lcmF0ZWQgIgorICAgICJ0b2tlbnMgYW5kIHthY3Rpb25zfSBhY3Rpb25zIG9u"
    "IHRoaXMgbGV2ZWwgd2l0aG91dCBjb21wbGV0aW5nIGl0LiBOb3RoaW5nIGhhcyAiCisgICAgImJl"
    "ZW4gcmVtb3ZlZCBmcm9tIHlvdXIgY29udGV4dCBhbmQgdGhlIGdhbWUgd2FzIG5vdCB0b3VjaGVk"
    "OyB0aGlzIGlzIGEgcm91dGluZSAiCisgICAgImNoZWNrcG9pbnQuIEJlZm9yZSBhY3RpbmcgZnVy"
    "dGhlciwgcmV2aWV3IHlvdXIgb3duIHJlYXNvbmluZyBvbiB0aGlzIGxldmVsOlxuIgorICAgICIx"
    "LiBMaXN0IHRoZSBpZGVhcyBhYm91dCB0aGUgY29udHJvbHMgYW5kIHRoZSBnb2FsIHRoYXQgeW91"
    "IGhhdmUgY29uc2lkZXJlZCBvbiAiCisgICAgInRoaXMgbGV2ZWwsIGluY2x1ZGluZyB0aGUgb25l"
    "cyB5b3UgcmVqZWN0ZWQuXG4iCisgICAgIjIuIEZvciBlYWNoIHJlamVjdGVkIGlkZWEsIG5hbWUg"
    "dGhlIHRlc3QgdGhhdCBydWxlZCBpdCBvdXQgYW5kIGNoZWNrIHdoZXRoZXIgdGhhdCAiCisgICAg"
    "InRlc3Qgd2FzIGZhaXIuIFdlcmUgaXRzIHByZWNvbmRpdGlvbnMgdHJ1ZSBhdCB0aGUgdGltZSAo"
    "dGhlIHN0YXRlLCBzaXplIGFuZCAiCisgICAgInBvc2l0aW9uIG9mIHRoZSBvYmplY3RzIGludm9s"
    "dmVkKT8gRGlkIHlvdSBjaGVjayB0aGUgd2hvbGUgYm9hcmQsIGV2ZXJ5IGNvbG91ciAiCisgICAg"
    "ImFuZCBvYmplY3QsIHJhdGhlciB0aGFuIG9uZSBleHBlY3RlZCBzcG90PyBEaWQgeW91IHdhdGNo"
    "IGxvbmcgZW5vdWdoPyBFZmZlY3RzIGNhbiAiCisgICAgImFwcGVhciBzZXZlcmFsIGFjdGlvbnMg"
    "bGF0ZXIgb3IgYmUgaGlkZGVuIHVuZGVyIGFub3RoZXIgb2JqZWN0LiBEaWQgeW91IHRyeSB0aGUg"
    "IgorICAgICJjb21wbGV0ZSB2ZXJzaW9uIG9mIHRoZSBpZGVhLCBvciBvbmx5IGEgZnJhZ21lbnQg"
    "b2YgaXQ/XG4iCisgICAgIjMuIEEgcmVqZWN0ZWQgaWRlYSB0aGF0IHdvdWxkIGV4cGxhaW4gd2h5"
    "IHRoZSBsZXZlbCdzIG9iamVjdHMgYXJlIHRoZXJlLCBidXQgd2FzICIKKyAgICAicnVsZWQgb3V0"
    "IGJ5IGFuIHVuZmFpciB0ZXN0LCBpcyB5b3VyIGJlc3QgY2FuZGlkYXRlOiByZS10ZXN0IGl0IHBy"
    "b3Blcmx5IHdpdGggdGhlICIKKyAgICAiY2hlYXBlc3QgdGVzdCB0aGF0IHdvdWxkIGNsZWFybHkg"
    "Y29uZmlybSBvciByZWZ1dGUgaXQuXG4iCisgICAgIklmIG5vIHJlamVjdGVkIGlkZWEgcXVhbGlm"
    "aWVzLCBzYXkgc28gYnJpZWZseSBhbmQgY29udGludWUgd2l0aCB0aGUgbW9zdCAiCisgICAgImlu"
    "Zm9ybWF0aXZlIGFjdGlvbiB5b3UgaGF2ZSBub3QgdHJpZWQgeWV0LiBLZWVwIHRoZSByZXZpZXcg"
    "c2hvcnQuIgorKQorCisKIGRlZiBfY29udGFpbnNfdG9vbF9jYWxsX21hcmt1cCgqY2h1bmtzOiBz"
    "dHIpIC0+IGJvb2w6CiAgICAgZm9yIGNodW5rIGluIGNodW5rczoKICAgICAgICAgbG93ZXJlZCA9"
    "IGNodW5rLmxvd2VyKCkKQEAgLTM1NzAsNiArMzYyMSwxMiBAQCBjbGFzcyBUb29sQWdlbnQ6CiAg"
    "ICAgICAgICkKICAgICAgICAgc2VsZi5fcmVzdW1lX2FmdGVyX3lpZWxkOiBib29sID0gRmFsc2UK"
    "ICAgICAgICAgc2VsZi5fcmVzdW1lX3JlYXNvbjogc3RyID0gIiIKKyAgICAgICAgIyBBUkMzX1NU"
    "VUNLX1JFVklFV19UT0tFTlM6IHJldmlldyBjaGVja3BvaW50cyBwZXIgbGV2ZWwuIFVuZGVyIHRo"
    "ZSBBL0IKKyAgICAgICAgIyBzd2l0Y2ggYSBnYW1lIHN0YXlzIHdpdGhvdXQgdGhlbSB1bnRpbCB0"
    "aGUgc29sdmVyIGFzc2lnbnMgaXRzIGFybS4KKyAgICAgICAgc2VsZi5fc3R1Y2tfcmV2aWV3X2Fj"
    "dGl2ZTogYm9vbCA9IG5vdCBfc3R1Y2tfcmV2aWV3X2FiKCkKKyAgICAgICAgc2VsZi5fc3R1Y2tf"
    "cmV2aWV3X2xldmVsOiBBbnkgPSBOb25lCisgICAgICAgIHNlbGYuX3N0dWNrX3Jldmlld19jb3Vu"
    "dDogaW50ID0gMAorICAgICAgICBzZWxmLl9zdHVja19yZXZpZXdfZXZlbnRzOiBsaXN0W2RpY3Rb"
    "c3RyLCBBbnldXSA9IFtdCiAgICAgICAgIHNlbGYuX3ByZXZfbGV2ZWxfc3RhcnRfZnJhbWU6IEZy"
    "YW1lIHwgTm9uZSA9IE5vbmUKICAgICAgICAgc2VsZi5fY3VyX2xldmVsX3N0YXJ0X2ZyYW1lOiBG"
    "cmFtZSB8IE5vbmUgPSBOb25lCiAgICAgICAgIHNlbGYuX2RlYXRoX2xlZGdlcl9sZXZlbDogQW55"
    "ID0gTm9uZQpAQCAtMzU4Niw2ICszNjQzLDcxIEBAIGNsYXNzIFRvb2xBZ2VudDoKICAgICAgICAg"
    "c2VsZi5fbGFzdF9hY3Rpb25fY2FsbF9yZXN1bHQ6IGRpY3Rbc3RyLCBBbnldIHwgTm9uZSA9IE5v"
    "bmUKICAgICAgICAgc2VsZi5fc3VtbWFyaXplZF9rbm93bGVkZ2UgPSBfZW1wdHlfd29ybGRfbW9k"
    "ZWwoKQogCisgICAgZGVmIGNvbmZpZ3VyZV9zdHVja19yZXZpZXcoc2VsZiwgZ2FtZV9pZDogc3Ry"
    "LCBwYXNzX2luZGV4OiBpbnQpIC0+IE5vbmU6CisgICAgICAgICIiIkNhbGxlZCBieSB0aGUgc29s"
    "dmVyIG9uY2UgaXQga25vd3Mgd2hpY2ggZ2FtZSBhbmQgcGFzcyB0aGlzIGFnZW50IHBsYXlzLiIi"
    "IgorICAgICAgICBzZWxmLl9zdHVja19yZXZpZXdfYWN0aXZlID0gKAorICAgICAgICAgICAgX3N0"
    "dWNrX3Jldmlld19hcm1fb24oZ2FtZV9pZCwgcGFzc19pbmRleCkgaWYgX3N0dWNrX3Jldmlld19h"
    "YigpIGVsc2UgVHJ1ZQorICAgICAgICApCisKKyAgICBAcHJvcGVydHkKKyAgICBkZWYgc3R1Y2tf"
    "cmV2aWV3X2FybShzZWxmKSAtPiBzdHI6CisgICAgICAgICIiIidvbicgb3IgJ29mZicgd2hpbGUg"
    "cmV2aWV3cyBhcmUgY29uZmlndXJlZCwgJycgd2hlbiB0aGV5IGFyZSBkaXNhYmxlZC4iIiIKKyAg"
    "ICAgICAgaWYgX3N0dWNrX3Jldmlld190b2tlbnMoKSA8PSAwOgorICAgICAgICAgICAgcmV0dXJu"
    "ICIiCisgICAgICAgIHJldHVybiAib24iIGlmIHNlbGYuX3N0dWNrX3Jldmlld19hY3RpdmUgZWxz"
    "ZSAib2ZmIgorCisgICAgQHByb3BlcnR5CisgICAgZGVmIHN0dWNrX3Jldmlld19ldmVudHMoc2Vs"
    "ZikgLT4gbGlzdFtkaWN0W3N0ciwgQW55XV06CisgICAgICAgICIiIkVhY2ggcmV2aWV3IHRoaXMg"
    "Z2FtZSByZWFjaGVkOiBmaXJlZCwgb3Igb25seSByZWNvcmRlZCBvbiB0aGUgQS9CIGFybSB3aXRo"
    "b3V0IHRoZW0uIiIiCisgICAgICAgIHJldHVybiBsaXN0KGdldGF0dHIoc2VsZiwgIl9zdHVja19y"
    "ZXZpZXdfZXZlbnRzIiwgTm9uZSkgb3IgW10pCisKKyAgICBkZWYgX21heWJlX3N0dWNrX3Jldmll"
    "dyhzZWxmLCBjdXJyZW50X2ZyYW1lOiBGcmFtZSB8IE5vbmUpIC0+IHN0ciB8IE5vbmU6CisgICAg"
    "ICAgICIiIkFzayB0aGUgbW9kZWwgdG8gcmV2aWV3IGl0cyByZWplY3RlZCBpZGVhcyBvbmNlIGEg"
    "bGV2ZWwgaGFzIHVzZWQgdG9vIG1hbnkgdG9rZW5zLgorCisgICAgICAgIFJldHVybnMgdGhlIG5v"
    "dGUgdG8gcHV0IGF0IHRoZSB0b3Agb2YgdGhpcyB0dXJuJ3Mgb3BlbmluZyBwcm9tcHQsIG9yIE5v"
    "bmUuCisgICAgICAgIE5vdGhpbmcgaXMgcmVtb3ZlZCBmcm9tIHRoZSBoaXN0b3J5IGFuZCBubyBj"
    "b3VudGVyIHRoZSBzY2hlZHVsZXIgdXNlcyBpcworICAgICAgICB0b3VjaGVkLiBNZWFzdXJlZCBv"
    "biB0aGUgZ2VuZXJhdGVkIHRva2VucyBzaW5jZSB0aGUgbGV2ZWwgYmVnYW47IHJldmlldworICAg"
    "ICAgICBuIG9uIGEgbGV2ZWwgZmlyZXMgYXQgbiB0aW1lcyB0aGUgdGhyZXNob2xkLgorICAgICAg"
    "ICAiIiIKKyAgICAgICAgdGhyZXNob2xkID0gX3N0dWNrX3Jldmlld190b2tlbnMoKQorICAgICAg"
    "ICBpZiB0aHJlc2hvbGQgPD0gMCBvciBjdXJyZW50X2ZyYW1lIGlzIE5vbmU6CisgICAgICAgICAg"
    "ICByZXR1cm4gTm9uZQorICAgICAgICBsZXZlbCA9IGludChjdXJyZW50X2ZyYW1lLmxldmVsKQor"
    "ICAgICAgICBpZiBzZWxmLl9zdHVja19yZXZpZXdfbGV2ZWwgIT0gbGV2ZWw6CisgICAgICAgICAg"
    "ICBzZWxmLl9zdHVja19yZXZpZXdfbGV2ZWwgPSBsZXZlbAorICAgICAgICAgICAgc2VsZi5fc3R1"
    "Y2tfcmV2aWV3X2NvdW50ID0gMAorICAgICAgICBpZiBzZWxmLl9zdHVja19yZXZpZXdfY291bnQg"
    "Pj0gX3N0dWNrX3Jldmlld19tYXhfcGVyX2xldmVsKCk6CisgICAgICAgICAgICByZXR1cm4gTm9u"
    "ZQorICAgICAgICB0b2tlbnNfb25fbGV2ZWwgPSBtYXgoCisgICAgICAgICAgICAwLCBzZWxmLl9z"
    "ZXNzaW9uX2dlbmVyYXRlZF90b2tlbnMgLSBnZXRhdHRyKHNlbGYsICJfdG9rZW5zX2F0X2xldmVs"
    "X3N0YXJ0IiwgMCkKKyAgICAgICAgKQorICAgICAgICBpZiB0b2tlbnNfb25fbGV2ZWwgPCB0aHJl"
    "c2hvbGQgKiAoc2VsZi5fc3R1Y2tfcmV2aWV3X2NvdW50ICsgMSk6CisgICAgICAgICAgICByZXR1"
    "cm4gTm9uZQorICAgICAgICBzdW1tYXJ5ID0gc2VsZi5fbGFzdF9zdGVwX3N1bW1hcnkgb3Ige30K"
    "KyAgICAgICAgaWYgc3VtbWFyeS5nZXQoInJ1bl9jb21wbGV0ZSIpOgorICAgICAgICAgICAgcmV0"
    "dXJuIE5vbmUKKyAgICAgICAgYWN0aW9uc19vbl9sZXZlbCA9IG1heCgKKyAgICAgICAgICAgIDAs"
    "IF9wcmlvcml0eV9hY3Rpb25fY291bnQoc3VtbWFyeSkgLSBnZXRhdHRyKHNlbGYsICJfYWN0aW9u"
    "c19hdF9sZXZlbF9zdGFydCIsIDApCisgICAgICAgICkKKyAgICAgICAgc2VsZi5fc3R1Y2tfcmV2"
    "aWV3X2NvdW50ICs9IDEKKyAgICAgICAgc2VsZi5fc3R1Y2tfcmV2aWV3X2V2ZW50cy5hcHBlbmQo"
    "eworICAgICAgICAgICAgImxldmVsIjogbGV2ZWwsCisgICAgICAgICAgICAicmV2aWV3Ijogc2Vs"
    "Zi5fc3R1Y2tfcmV2aWV3X2NvdW50LAorICAgICAgICAgICAgInRva2Vuc19vbl9sZXZlbCI6IHRv"
    "a2Vuc19vbl9sZXZlbCwKKyAgICAgICAgICAgICJhY3Rpb25zX29uX2xldmVsIjogYWN0aW9uc19v"
    "bl9sZXZlbCwKKyAgICAgICAgICAgICJmaXJlZCI6IGJvb2woc2VsZi5fc3R1Y2tfcmV2aWV3X2Fj"
    "dGl2ZSksCisgICAgICAgIH0pCisgICAgICAgIGlmIG5vdCBzZWxmLl9zdHVja19yZXZpZXdfYWN0"
    "aXZlOgorICAgICAgICAgICAgcmV0dXJuIE5vbmUKKyAgICAgICAgbG9nLndhcm5pbmcoCisgICAg"
    "ICAgICAgICAiJXM6IHJldmlldyBjaGVja3BvaW50ICVkIG9uIGxldmVsICVkIGFmdGVyICVkIGdl"
    "bmVyYXRlZCB0b2tlbnMgYW5kICVkIGFjdGlvbnMiLAorICAgICAgICAgICAgZ2V0YXR0cihzZWxm"
    "LCAiX2RpYWdfbmFtZSIsICI/IiksIHNlbGYuX3N0dWNrX3Jldmlld19jb3VudCwgbGV2ZWwsCisg"
    "ICAgICAgICAgICB0b2tlbnNfb25fbGV2ZWwsIGFjdGlvbnNfb25fbGV2ZWwsCisgICAgICAgICkK"
    "KyAgICAgICAgcmV0dXJuIF9TVFVDS19SRVZJRVdfTk9URS5mb3JtYXQoCisgICAgICAgICAgICBs"
    "ZXZlbD1sZXZlbCwgdG9rZW5zX2s9cm91bmQodG9rZW5zX29uX2xldmVsIC8gMTAwMCksIGFjdGlv"
    "bnM9YWN0aW9uc19vbl9sZXZlbCwKKyAgICAgICAgKQorCiAgICAgZGVmIF9oZWFkZXJzKHNlbGYp"
    "IC0+IGRpY3Rbc3RyLCBzdHJdOgogICAgICAgICBhcGlfa2V5ID0gKAogICAgICAgICAgICAgc2Vs"
    "Zi5fYXBpX2tleQpAQCAtNjU5NCw2ICs2NzE2LDE3IEBAIGNsYXNzIFRvb2xBZ2VudDoKICAgICAg"
    "ICAgKQogICAgICAgICBkaXNwbGF5X2FjdGlvbl9udW0gPSBfZGlzcGxheV9hY3Rpb25fbnVtYmVy"
    "KGFjdGlvbl9udW0pCiAgICAgICAgIHNlbGYuX3dtX2Fic29yYmVkX2luX3R1cm4gPSBGYWxzZQor"
    "ICAgICAgICByZXZpZXdzX2JlZm9yZSA9IGxlbihzZWxmLl9zdHVja19yZXZpZXdfZXZlbnRzKQor"
    "ICAgICAgICBzdHVja19yZXZpZXdfbm90ZSA9IHNlbGYuX21heWJlX3N0dWNrX3JldmlldyhjdXJy"
    "ZW50X2ZyYW1lKQorICAgICAgICBzdHVja19yZXZpZXdfZXZlbnQgPSAoCisgICAgICAgICAgICBz"
    "ZWxmLl9zdHVja19yZXZpZXdfZXZlbnRzWy0xXQorICAgICAgICAgICAgaWYgbGVuKHNlbGYuX3N0"
    "dWNrX3Jldmlld19ldmVudHMpID4gcmV2aWV3c19iZWZvcmUgZWxzZSBOb25lCisgICAgICAgICkK"
    "KyAgICAgICAgaWYgc3R1Y2tfcmV2aWV3X25vdGUgaXMgbm90IE5vbmU6CisgICAgICAgICAgICB1"
    "c2VyX3Byb21wdCA9IGYie3N0dWNrX3Jldmlld19ub3RlfVxuXG57dXNlcl9wcm9tcHR9IgorICAg"
    "ICAgICAgICAgIyBhIHNob3J0IHJlc3VtcHRpb24gcHJvbXB0IHdvdWxkIGRyb3AgdGhlIG5vdGU6"
    "IHNlbmQgdGhlIGZ1bGwKKyAgICAgICAgICAgICMgb3BlbmVyLCB3aXRoIHRoZSBjdXJyZW50IGJv"
    "YXJkLCBmb3IgdGhpcyBvbmUgdHVybgorICAgICAgICAgICAgc2VsZi5fcmVzdW1lX2FmdGVyX3lp"
    "ZWxkID0gRmFsc2UKIAogICAgICAgICB3aXRoIG9wZW4oYW5hbHl6ZXJfbG9nLCAiYSIsIGVuY29k"
    "aW5nPSJ1dGYtOCIpIGFzIGY6CiAgICAgICAgICAgICBzdGVwX2xhYmVsID0gZiJhbmFseXNpc19z"
    "dGVwPXthbmFseXNpc19zdGVwfSB8ICIgaWYgYW5hbHlzaXNfc3RlcCBpcyBub3QgTm9uZSBlbHNl"
    "ICIiCkBAIC02Njc4LDYgKzY4MTEsMTAgQEAgY2xhc3MgVG9vbEFnZW50OgogICAgICAgICAgICAg"
    "b3BlbmluZ19tZXNzYWdlID0gc2VsZi5fYnVpbGRfdXNlcl9tZXNzYWdlKAogICAgICAgICAgICAg"
    "ICAgIHVzZXJfcHJvbXB0LCByZXN1bWVfZnJhbWUgaWYgcmVzdW1pbmdfYWZ0ZXJfeWllbGQgZWxz"
    "ZSBjdXJyZW50X2ZyYW1lCiAgICAgICAgICAgICApCisgICAgICAgIGlmIHN0dWNrX3Jldmlld19l"
    "dmVudCBpcyBub3QgTm9uZToKKyAgICAgICAgICAgIGFwcGVuZF90cmFuc2NyaXB0KAorICAgICAg"
    "ICAgICAgICAgICJBTkFMWVpFUiBTVEFUVVMiLCAic3R1Y2tfcmV2aWV3OiAiICsganNvbi5kdW1w"
    "cyhzdHVja19yZXZpZXdfZXZlbnQsIHNvcnRfa2V5cz1UcnVlKQorICAgICAgICAgICAgKQogICAg"
    "ICAgICAjIGxvZyB3aGF0IHdhcyBhY3R1YWxseSBTRU5ULCBub3QgdGhlIGFyZ3VtZW50IHRoYXQg"
    "d2FzIHBhc3NlZCBpbjogb24gYQogICAgICAgICAjIHJlc3VtZWQgaW52b2NhdGlvbiB0aGUgc2hv"
    "cnQvc3RhdGVfb25seSBzdWJzdGl0dXRpb24gaGFwcGVucyBoZXJlLCBzbwogICAgICAgICAjIHRy"
    "YW5zY3JpYmluZyBgdXNlcl9wcm9tcHRgIHdvdWxkIHJlcG9ydCBhIGZ1bGwgb3BlbmVyIHRoZSBt"
    "b2RlbCBuZXZlcgpkaWZmIC0tZ2l0IGEvQVJDMy1JbmZlcmVuY2UvaW5mZXJlbmNlL2ZyYW1ld29y"
    "ay9zb2x2ZXIucHkgYi9BUkMzLUluZmVyZW5jZS9pbmZlcmVuY2UvZnJhbWV3b3JrL3NvbHZlci5w"
    "eQppbmRleCBlNDA5NzZjLi5iMDMxYTQ1IDEwMDY0NAotLS0gYS9BUkMzLUluZmVyZW5jZS9pbmZl"
    "cmVuY2UvZnJhbWV3b3JrL3NvbHZlci5weQorKysgYi9BUkMzLUluZmVyZW5jZS9pbmZlcmVuY2Uv"
    "ZnJhbWV3b3JrL3NvbHZlci5weQpAQCAtNzM4LDYgKzczOCwxNyBAQCBjbGFzcyBfSGFybmVzc0dh"
    "bWVTZXNzaW9uOgogICAgICAgICAgICAgdG90YWxfdG9rZW5zID0gX2FuYWx5emVyX3JlcG9ydGVk"
    "X3Rva2VucyhzZWxmLmFuYWx5emVyKQogICAgICAgICAgICAgaWYgcnVuLnNvbHZlcl9ub3RlIGlz"
    "IE5vbmU6CiAgICAgICAgICAgICAgICAgcnVuLnNvbHZlcl9ub3RlID0gZiJ0b2tlbnM9e3RvdGFs"
    "X3Rva2Vuc30iCisgICAgICAgICAgICAgICAgIyBBUkMzX1NUVUNLX1JFVklFV19UT0tFTlM6IHRo"
    "ZSBBL0IgYXJtIGFuZCBlYWNoIHJldmlldyBhcworICAgICAgICAgICAgICAgICMgbGV2ZWxAdG9r"
    "ZW5zLW9uLWxldmVsLCBzbyBiZW5jaG1hcmsuanNvbiBjYXJyaWVzIHRoZW0KKyAgICAgICAgICAg"
    "ICAgICBhcm0gPSBnZXRhdHRyKHNlbGYuYW5hbHl6ZXIsICJzdHVja19yZXZpZXdfYXJtIiwgIiIp"
    "CisgICAgICAgICAgICAgICAgaWYgYXJtOgorICAgICAgICAgICAgICAgICAgICBydW4uc29sdmVy"
    "X25vdGUgKz0gZiIgcmV2aWV3X2FybT17YXJtfSIKKyAgICAgICAgICAgICAgICAgICAgcmV2aWV3"
    "cyA9IGdldGF0dHIoc2VsZi5hbmFseXplciwgInN0dWNrX3Jldmlld19ldmVudHMiLCBOb25lKSBv"
    "ciBbXQorICAgICAgICAgICAgICAgICAgICBpZiByZXZpZXdzOgorICAgICAgICAgICAgICAgICAg"
    "ICAgICAgcnVuLnNvbHZlcl9ub3RlICs9ICIgcmV2aWV3cz0iICsgIiwiLmpvaW4oCisgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgZiJ7aW50KGV2ZW50WydsZXZlbCddKX1Ae2ludChldmVudFsn"
    "dG9rZW5zX29uX2xldmVsJ10pfSIKKyAgICAgICAgICAgICAgICAgICAgICAgICAgICBmb3IgZXZl"
    "bnQgaW4gcmV2aWV3cworICAgICAgICAgICAgICAgICAgICAgICAgKQogICAgICAgICAgICAgc2Vs"
    "Zi5fZmluaXNoX2lmX25lZWRlZCgpCiAgICAgICAgICAgICBzZWxmLnN0YXRlX3BhdGgudW5saW5r"
    "KG1pc3Npbmdfb2s9VHJ1ZSkKICAgICAgICAgICAgIHNlbGYuX3dyaXRlX2FuYWx5c2lzX2h0bWwo"
    "KQpAQCAtMTg2OSw2ICsxODgwLDggQEAgY2xhc3MgSGFybmVzc1NvbHZlcihTb2x2ZXIpOgogICAg"
    "ICAgICAgICAgdHJhbnNjcmlwdF9wYXRoID0gc2VsZi5fdHJhbnNjcmlwdHNfZGlyKCkgLyBmInty"
    "dW5fc3RlbX0udHh0IgogICAgICAgICAgICAgYW5hbHlzaXNfcmVscGF0aCA9IGYic29sdmVyX2Fu"
    "YWx5c2lzL3tydW5fc3RlbX0uaHRtbCIKICAgICAgICAgICAgIGFuYWx5emVyID0gc2VsZi5fbWFr"
    "ZV9hbmFseXplcihnYW1lLCBpbmRleCwgbG9jYWxfc2VydmVyKQorICAgICAgICAgICAgaWYgaGFz"
    "YXR0cihhbmFseXplciwgImNvbmZpZ3VyZV9zdHVja19yZXZpZXciKToKKyAgICAgICAgICAgICAg"
    "ICBhbmFseXplci5jb25maWd1cmVfc3R1Y2tfcmV2aWV3KHJ1bi5nYW1lX2lkLCBwYXNzX2luZGV4"
    "KQogICAgICAgICAgICAgc2Vzc2lvbiA9IF9IYXJuZXNzR2FtZVNlc3Npb24oCiAgICAgICAgICAg"
    "ICAgICAgc29sdmVyPXNlbGYsCiAgICAgICAgICAgICAgICAgZ2FtZT1nYW1lLAo="
)
_patch = base64.b64decode("".join(_PATCH_B64.split()))
assert hashlib.sha256(_patch).hexdigest() == _PATCH_SHA256, (
    "stuck-review patch was damaged while copying: re-copy this whole cell"
)
_src = f"{BUNDLE_DIR}/src"
_agent_py = Path(_src) / "ARC3-Inference/inference/agent/tool_agent.py"
if "ARC3_FRESH_START_TOKENS" in _agent_py.read_text():
    raise RuntimeError(
        "The old fresh-start cell is still in this notebook: delete it, then run all cells again."
    )
_patch_path = Path("/kaggle/stuck-review.patch")
_patch_path.write_bytes(_patch)
_git = ["git", "apply", "--include=ARC3-Inference/*"]
if subprocess.run(_git + ["-R", "--check", str(_patch_path)], cwd=_src, capture_output=True).returncode == 0:
    print("stuck review: patch already applied")
else:
    subprocess.run(_git + ["-v", str(_patch_path)], cwd=_src, check=True)
os.environ["ARC3_STUCK_REVIEW_TOKENS"] = str(int(REVIEW_TOKENS))
os.environ["ARC3_STUCK_REVIEW_MAX"] = str(int(REVIEW_MAX))
os.environ["ARC3_STUCK_REVIEW_AB"] = "1" if AB_TEST else "0"
print(
    f"stuck review: ARC3_STUCK_REVIEW_TOKENS={REVIEW_TOKENS}, ARC3_STUCK_REVIEW_MAX={REVIEW_MAX}, "
    f"A/B test {'ON (local measurement only)' if AB_TEST else 'off'}"
)
